Add pod-job model
walkerlab/orcapod pull request #43
Opened 2024-11-01 23:33 UTC by Synicix

2024-11-08 01:07 UTC, Synicix commented on src/model.rs
> +    input_volume_map: BTreeMap<PathBuf, PathBuf>,
File hash -> stream key. Bring this up for dicussion tomrrow.
Perhaps need to implement input / store first.

2024-11-08 14:02 UTC, guzman-raphael requested changes
A summary from our discussion yesterday is that your implementation of the current design is great and accurate here, however, I have some doubts about our design.

Mainly, feel that:
-  `Input` model should be implemented first (or with this PR) so that `PodJob` can have a reference to it (like how `PodJob` refers to a `Pod`).
- A stream's key doesn't seem to be referenced in `PodJob`. That way less things would break if there are updates to the associated `Pod`.

2024-11-16 08:45 UTC, Synicix commented
Summary of changes:
- Add pod job model
- Add save and load functions for store for the file store
- Add compute_check_sum for file or folder to the store trait and implmented it in filestore with merkle_hash for efficient computation (it uses Blake3 which is apprently faster than sha256, but need to actually indepdent test it)
- Add wipe functionailty for wiping entire store
- Change filestore functions to fully support annotationless operations
- Redesign filestore test to full test all model more parallelization

2024-12-12 10:03 UTC, Synicix reviewed
Old review

2024-12-12 10:03 UTC, Synicix commented on Cargo.toml
> +anyhow = "1.0.93"
move that down

2024-12-12 10:03 UTC, Synicix commented on src/error.rs
> +    FromUtf8Error(FromUtf8Error),
Might not needed anymore

2024-12-12 10:03 UTC, Synicix commented on src/error.rs
> +impl From<FromUtf8Error> for OrcaError {
Probably check if it is needed anymore

2024-12-12 10:03 UTC, Synicix commented on src/model.rs
> +    pub pod_hash: String,
Pod in memory and convert to hash in store

- hash

2024-12-12 10:03 UTC, Synicix commented on tests/fixture/mod.rs
> +        pod_style()?.hash,
Change pod style

2024-12-12 10:03 UTC, Synicix commented on src/model.rs
> +    pub version: String,
changee to version to annotations, and add hash to try

2024-12-12 10:03 UTC, Synicix commented on src/model.rs
> +    pub stores: BTreeMap<String, String>,
cut it down to just uri

2024-12-12 10:03 UTC, Synicix commented on src/error.rs
> +    FromUtf8Error(FromUtf8Error),
Still need them

2024-12-12 10:03 UTC, Synicix commented on Cargo.toml
> +anyhow = "1.0.93"
fixed

2024-12-12 10:03 UTC, Synicix commented on src/error.rs
> +impl From<FromUtf8Error> for OrcaError {
still need them

2024-12-12 10:03 UTC, Synicix commented on src/error.rs
> +impl From<FromUtf8Error> for OrcaError {
removed

2024-12-12 10:03 UTC, Synicix commented on src/model.rs
> +    pub pod_hash: String,
fixed

2024-12-12 10:03 UTC, Synicix commented on tests/fixture/mod.rs
> +        pod_style()?.hash,
fixed?

2024-12-12 10:03 UTC, Synicix commented on src/model.rs
> +    pub version: String,
update to new desgin

2024-12-12 10:03 UTC, Synicix commented on src/model.rs
> +    pub stores: BTreeMap<String, String>,
change to uri

2024-12-17 01:21 UTC, Synicix commented on src/model.rs
> +        let storage_class_name = self.uri.split("::").collect::<Vec<&str>>()[0];
change it to // instead of ;:

2024-12-17 10:48 UTC, Synicix reviewed
Notes from meeting

2024-12-17 10:48 UTC, Synicix commented on src/store/mod.rs
> +pub trait FileStore: Sized {
Change name to data store

2024-12-17 10:48 UTC, Synicix commented on src/store/mod.rs
> +pub trait ModelStore: Sized {
Add filestore as a trait dependency

2024-12-17 10:48 UTC, Synicix commented on tests/model.rs
> +#[test]
Add data store trait tests

2024-12-17 10:48 UTC, Synicix commented on tests/model.rs
> +#[test]
Defer till orchestrator

2024-12-17 10:48 UTC, Synicix commented on src/store/mod.rs
> +pub trait ModelStore: Sized {
fixe

2024-12-17 10:48 UTC, Synicix commented on src/store/mod.rs
> +pub trait FileStore: Sized {
fixed

2024-12-17 10:50 UTC, Synicix commented
Changes made, ready for review @eywalker @guzman-raphael

2025-01-24 15:32 UTC, guzman-raphael approved these changes

2025-01-24 15:32 UTC, guzman-raphael commented on Cargo.toml
> +image = "0.25.5"
This appears to be a dev-dependency since it is only utilized in the tests.

2025-01-24 15:32 UTC, guzman-raphael commented on src/lib.rs
> +/// Open utils for test to use
This comment is unnecessary. Seems like a note as opposed to documenting the `util` module.

2025-01-24 15:32 UTC, guzman-raphael commented on src/util.rs
> +/// Never will panic
Unneeded documentation of private method.

2025-01-24 15:32 UTC, guzman-raphael commented on src/util.rs
> +/// Standard hashing algorithm for models
Unneeded documentation of private method.

2025-01-24 15:35 UTC, merged