`LocalDockerOrchestrator` support
walkerlab/orcapod pull request #44
Opened 2024-11-08 14:17 UTC by guzman-raphael

2025-02-03 08:36 UTC, Synicix commented on cspell.json
What is this for?

2025-02-03 08:38 UTC, Synicix commented on src/model.rs
>      source_commit_url: String,
We should put a comment on what this is and also discussed about it since it doesn't really affect repoduceabilty at all

2025-02-03 08:38 UTC, Synicix commented on cspell.json
Not sure what this is for

2025-02-03 08:39 UTC, Synicix commented on src/model.rs
> +    pub env_vars: Option<HashMap<String, String>>,
Hmm, this is one thing that slip through the cracks. Good addition

2025-02-03 23:19 UTC, Synicix commented on src/model.rs
> +fn serialize_pod_job<S>(pod_job: &PodJob, serializer: S) -> result::Result<S::Ok, S::Error>
I guess we went back to the old impl?

2025-02-03 23:26 UTC, Synicix commented on src/model.rs
> +    #[serde(
Perhaps we don't need the pod deseralizer function at all, because skip techincallly does what the current deseralize does

2025-02-03 23:27 UTC, Synicix commented on src/model.rs
> +fn deserialize_pod_job<'de, D>(deserializer: D) -> result::Result<PodJob, D::Error>
Same thing as pod, I recall skip with default would allow this behavior to be done

2025-02-03 23:27 UTC, Synicix commented on src/model.rs
> +    serializer.serialize_str(&pod_job.hash)
This still saves the rest of the fields?

2025-02-03 23:28 UTC, Synicix commented on src/model.rs
> +        annotation: Option<Annotation>,
What would be store here in annotation?

2025-02-03 23:29 UTC, Synicix commented on src/model.rs
> +        state: RunState,
Run state seems a bit wrong for the struct name, perhaps just State

2025-02-03 23:30 UTC, Synicix commented on src/orchestrator/mod.rs
> +pub enum RunState {
Should probably rename to just State due to the usage in pod result. Also perhaps move this to utils since it is used by mutiple modules?

2025-02-03 23:31 UTC, Synicix commented on src/orchestrator/mod.rs
> +pub enum RunState {
Also is there no option for queuing? Sometimes orcherstrator might have max jobs already running like in K8 and has to wait their turn

2025-02-03 23:33 UTC, Synicix commented on src/orchestrator/mod.rs
> +    pub env_vars: HashMap<String, String>,
Noticed that there is no reference to pod_job. Should probably discuss the pro and cons about it.

2025-02-03 23:35 UTC, Synicix commented on src/orchestrator/mod.rs
> +pub trait PodRunAPI: Types {
Is there a way to get current logs. (Okay if not implemented yet)

2025-02-03 23:37 UTC, Synicix commented on src/store/filestore.rs
> +#[expect(clippy::unwrap_used, reason = "Valid static regex")]
Hmm, nice we don't have to redo thsi every time

2025-02-03 23:38 UTC, Synicix commented on src/store/filestore.rs
> -    /// Get the directory where store is located.
Agreee with the removal of this, since I removed it too initially before the last pull request

2025-02-03 23:38 UTC, Synicix commented on src/store/filestore.rs
> +    /// Get the directory where store is located.
Oh it got reorderd. Okay maybe let see if we need this, because can't these just be public?

2025-02-03 23:48 UTC, Synicix commented on src/orchestrator/docker.rs
> +        let container_name = Generator::with_naming(Name::Plain)
Need to look up how this works

2025-02-03 23:55 UTC, Synicix commented on src/orchestrator/docker.rs
> +        filters: HashMap<String, Vec<String>>,
Perhaps add docs on what these filters can be

2025-02-03 23:57 UTC, Synicix commented on src/model.rs
> +    pub created: u64,
Perhaps consider using sered_with date time?

2025-02-04 00:41 UTC, Synicix commented on src/model.rs
>      source_commit_url: String,
TODO; Create an issue about this to dicuss later

2025-02-04 00:44 UTC, Synicix commented on src/model.rs
> +    pub env_vars: Option<HashMap<String, String>>,
Create an issue on env_var where it should probably be put in pod and not pod-job, with pod-job ability to override.

2025-02-04 01:01 UTC, Synicix commented on src/model.rs
> +    pub created: u64,
Create and issue of doing custom seralization of datetime and throw it in utils.rs

2025-02-04 01:23 UTC, Synicix commented on src/model.rs
> +        state: RunState,
Already renamed by raphael

2025-02-04 01:30 UTC, Synicix commented on src/orchestrator/mod.rs
> +pub enum RunState {
Make an issue about either finding a way to deal with it via enum inheratince (don't think there either)
Other resolved

2025-02-04 01:39 UTC, Synicix commented on src/orchestrator/mod.rs
> +pub trait PodRunAPI: Types {
For now: There is a work around by using the contianer name and fecthing the logs outside of  the orca system.

2025-02-07 01:40 UTC, Synicix commented on src/model.rs
>      source_commit_url: String,
We decided on perhaps moving it to a specific PodAnnotation that is seperate from Annotation. Should make it optional

2025-02-07 01:51 UTC, Synicix commented on src/model.rs
> +    pub env_vars: Option<HashMap<String, String>>,
Add issue to support ARGs also which is a Vec<String> (include as discussion where it should live, either in pod or podjob?)

For env variables same thing

2025-02-12 00:03 UTC, eywalker requested changes
Marking it as a change request but it's really to just raise a few discussion points on which I commented.

2025-02-12 00:03 UTC, eywalker commented on src/orchestrator/mod.rs
> +pub struct PodRun {
We might want to consider adding an attribute that would (loosely) indicate the type of orchestrator used. That may allow for the orchestrator to quickly determine if it's compatible with the kind of orchestrator that was used to create the pod run.

2025-02-12 00:03 UTC, eywalker commented on src/orchestrator/mod.rs
> +    fn get_result_async(&self, pod_run: &PodRun) -> impl Future<Output = Result<PodResult>> + Send;
I think I'd prefer to make this the `get_result` and make the synchronous version `get_result_sync` just because I'd imagine the async version to be the more common usecase. Thoughts?

2025-02-12 00:59 UTC, guzman-raphael commented on src/orchestrator/mod.rs
> +    fn get_result_async(&self, pod_run: &PodRun) -> impl Future<Output = Result<PodResult>> + Send;
You don't think it is confusing if some functions default to sync and some default to async? e.g. currently everything defaults to sync unless it has the `_async` suffix.

If we don't have this consistency, it would require developers to always check the function signature to be sure. How painful this is depends on how nice their DEV setup is.

2025-02-12 01:12 UTC, guzman-raphael commented on src/orchestrator/mod.rs
> +pub struct PodRun {
That seems reasonable. I'll add a version based on `String` here soon.

2025-02-12 11:03 UTC, Synicix commented on src/util.rs
> -pub fn get_type_name<T>() -> String {
Ask about why the change

2025-02-13 00:02 UTC, guzman-raphael commented on src/util.rs
> -pub fn get_type_name<T>() -> String {
This update was my take on @eywalker's [suggestion](https://github.com/walkerlab/orcapod/pull/44#discussion_r1951707177).

2025-02-17 07:19 UTC, Synicix approved these changes
looks good with the updates

2025-02-18 00:43 UTC, eywalker approved these changes

2025-02-18 00:44 UTC, merged